version: "3.8"

services:
  mysql-db:
    image: mysql:8.0.28
    container_name: mysql-db
    volumes:
      - my-db:/var/lib/mysql
    env_file:
      - ./env/mysql.env
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    env_file:
      - ./env/phpmyadmin.env
    restart: unless-stopped
    depends_on:
      - mysql-db

  python-backend:
    build: ./backend
    ports:
      - "120:80"
    env_file:
      - ./env/backend.env
    depends_on:
      - mysql-db

  nginx-frontend:
    build: ./frontend
    stdin_open: true
    tty: true
    ports:
      - "80:80"
    depends_on:
      - python-backend

volumes:
  my-db:
