version: "3.8"

services:
  mysql-db:
    image: mysql:8.0.28
    container_name: mysql-db
    volumes:
      - my-db:/var/lib/mysql
    env_file:
      - ./env/mysql.env
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "127.0.0.1:8080:80"
    env_file:
      - ./env/phpmyadmin.env
    restart: unless-stopped
    depends_on:
      - mysql-db

  python-backend:
    image: papajohn77/vrp-solver-backend
    ports:
      - "127.0.0.1:8000:80"
    env_file:
      - ./env/backend.env
    depends_on:
      - mysql-db

volumes:
  my-db:
